;1、域名组
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=DIRECT,https://raw.githubusercontent.com/hqw567/subconv-ruleforge/main/v1/rules/direct.list

ruleset=🌍 代理,https://raw.githubusercontent.com/hqw567/subconv-ruleforge/main/v1/rules/proxy.list
ruleset=🇨🇳 国内,https://raw.githubusercontent.com/hqw567/subconv-ruleforge/main/v1/rules/china.list
ruleset=🤖 AI,https://raw.githubusercontent.com/hqw567/subconv-ruleforge/main/v1/rules/ai.list

ruleset=🛑 广告,https://raw.githubusercontent.com/hqw567/subconv-ruleforge/main/v1/rules/ad.list
ruleset=🛑 广告,clash-classic:https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Clash-Classical.yaml

ruleset=🤖 AI,https://ruleset.skk.moe/Clash/non_ip/ai.txt

ruleset=🇨🇳 国内,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=🇨🇳 国内,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🇨🇳 国内,https://ruleset.skk.moe/Clash/non_ip/apple_cn.txt
ruleset=🇨🇳 国内,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🇨🇳 国内,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🇨🇳 国内,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🇨🇳 国内,https://ruleset.skk.moe/Clash/non_ip/direct.txt
ruleset=🇨🇳 国内,https://ruleset.skk.moe/Clash/domainset/game-download.txt
ruleset=🇨🇳 国内,https://ruleset.skk.moe/Clash/non_ip/domestic.txt
ruleset=🌍 代理,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list
ruleset=🇨🇳 国内,[]GEOIP,CN

ruleset=❓ 未知,[]FINAL

;2、策略组（域名组-节点组）
custom_proxy_group=🌍 代理`select`[]⚡ 自动`[]🎯 手动`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇸🇬 新加坡`[]🇰🇷 韩国`[]🇺🇲 美国`[]其他国家`[]DIRECT
custom_proxy_group=🎯 手动`select`.*`[]DIRECT
custom_proxy_group=⚡ 自动`url-test`.*`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🤖 AI`select`[]🌍 代理`[]⚡ 自动`[]🎯 手动`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇸🇬 新加坡`[]🇰🇷 韩国`[]🇺🇲 美国`[]其他国家`[]DIRECT
custom_proxy_group=❓ 未知`select`[]🌍 代理`[]⚡ 自动`[]🎯 手动`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇸🇬 新加坡`[]🇰🇷 韩国`[]🇺🇲 美国`[]其他国家`[]DIRECT
custom_proxy_group=🛑 广告`select`[]REJECT`[]DIRECT`[]🌍 代理
custom_proxy_group=🇨🇳 国内`select`[]DIRECT`[]🌍 代理`[]⚡ 自动`[]🎯 手动`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇸🇬 新加坡`[]🇰🇷 韩国`[]🇺🇲 美国`[]其他国家

;3、节点组
custom_proxy_group=🇭🇰 香港`url-test`(港|HK|hk|Hong Kong|HongKong|hongkong|🇭🇰)`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇺🇲 美国`url-test`(美|纽约|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|🇺🇲)`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇯🇵 日本`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan|🇯🇵)`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇸🇬 新加坡`url-test`(新加坡|坡|狮城|SG|Singapore|🇸🇬)`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇹🇼 台湾`url-test`(台|新北|彰化|TW|Tai Wan|TaiWan|Taiwan|🇹🇼)`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇰🇷 韩国`url-test`(KR|Korea|KOR|首尔|韩|韓|🇰🇷)`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=其他国家`url-test`(^(?!.*(港|HK|hk|Hong Kong|HongKong|hongkong|🇭🇰|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan|🇯🇵|KR|Korea|KOR|首尔|韩|韓|🇰🇷|新加坡|坡|狮城|SG|Singapore|🇸🇬|台|新北|彰化|TW|Tai Wan|TaiWan|Taiwan|🇹🇼|美|纽约|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|🇺🇲)).*)`http://www.gstatic.com/generate_204`300,,150

;4、启用规则集
enable_rule_generator=true
overwrite_original_rules=true
